### ISSUE TITLE
Laravel 5 error

### ISSUE THREAD

**Issue by peterlevin** [jelovac/bitly4laravel#25] opened 2015-11-16 19:21 UTC
Invalid variable type detected! The variable must be type "String", "NULL" type passed.

Followed instructions. 

Added use Bitly; to my controller and getting above error with:

$test = Bitly::shorten('http://google.com/');
        
return $test;

**Comment by peterlevin** [comment] 2015-11-16 19:26
hold up! Think i figured it out...stand by!

**Comment by peterlevin** [comment] 2015-11-16 19:36
Nope, can't figure it out. Added acccess token to config and can't get it to work.

**Comment by briff** [comment] 2016-02-17 17:13
Works for me out of the box on laravel 5.2

**Comment by jelovac** [comment] 2016-02-17 18:58
Couldn't reproduce this issue. Closing for now.

**Closed by jelovac** 2016-02-17 18:58 UTC

**Comment by freel132** [comment] 2016-04-16 00:50
have same issue
